# Generated by Django 4.1 on 2022-08-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='img',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
