# Generated by Django 4.1 on 2022-08-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_menuitem_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='description',
            new_name='desc',
        ),
    ]
