# Generated by Django 4.1 on 2022-08-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_recipe_instructions_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='Instructions',
            new_name='Instruction',
        ),
    ]
