# Generated by Django 4.1 on 2022-08-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
